default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_PATH") { "storage" } %>/development.sqlite3

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_PATH") { "storage" } %>/test.sqlite3

production:
  <<: *default
  databse: <%= ENV.fetch("DATABASE_PATH") { "storage" } %>/production.sqlite3
